apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nx-app-ingress
  namespace: nx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: nx.nonprod.stacks.ensono.com  # Replace with your domain or use a local host
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nx-app-service
            port:
              number: 80
  tls:
    - hosts:
        - nonprod.stacks.ensono.com
